In [4]:
import numpy as np
import math

In [5]:
def read_maze(filename):
    matrix = []
    nodes = []
    start = []
    end = []
    pointed_nodes = []
    start_index = 0
    end_index = 0
    count = 0
    size = []
    with open(filename) as f:
        line = f.readlines()
        f.close()
    for i in range(len(line)):
        line[i] = line[i].replace("\n","")
    line[0] = int(line[0])
    count = line[0]
    line.pop(0)
    for i in range(count):
        node = line[0].split()
        for j in range(3):
            node[j] = int(node[j])
        pointed_nodes.append(node)
        line.pop(0)
    row = len(line)
    size.append(row)
    column = len(line[0])
    size.append(column)
    for i in range(row):
        for j in range(column):
            if(line[i][j] == ' '):
                if(i == 0 or i==row-1):
                    end.append(i)
                    end.append(j)
                    nodes.append([i,j])
                    end_index = len(nodes)-1
                elif(j==0 or j == column-1):
                    end.append(i)
                    end.append(j)
                    nodes.append([i,j])
                    end_index = len(nodes)-1
                else:
                    nodes.append([i,j])
            elif(line[i][j]=='S'):
                start.append(i)
                start.append(j)
                nodes.append([i,j])
                start_index = len(nodes)-1
            elif(line[i][j]=='+'):
                nodes.append([i,j])
    point = []
    node = []
    for i in pointed_nodes:
        point.append(i.pop())
        node.append(i)
    for i in nodes:
        distance = []
        node_1 = [i[0]+1,i[1]]
        node_2 = [i[0]-1,i[1]]
        node_3 = [i[0],i[1]+1]
        node_4 = [i[0],i[1]-1]
        for j in nodes:
            if(i==j):
                distance.append(0)
            elif(j==node_1 or j ==node_2 or j==node_3 or j==node_4):
                if(j in node):
                    distance.append(point[node.index(j)])
                else:
                    distance.append(1)
            else:
                distance.append(0)
        matrix.append(distance)
    matrix = np.array(matrix)
    h = []
    for i in nodes:
        value = ((i[0]-end[0])**2) + ((i[1]-end[1])**2)
        value = math.sqrt(value)
        h.append(value)
    return matrix, nodes,pointed_nodes, start, end, start_index, end_index,size,h

In [6]:
def DFS(matrix,start,end):
    path=[]
    explored={}
    frontier={}
    frontier[start]=None
    k=start
    while True:
        if len(frontier)==0:
            result='No path'
            return list(explored),result
        res=list(frontier.keys())[-1]
        point=frontier.pop(res)
        explored[res]=point
        value=0
        k=0
        for i in matrix[res]:
            if (i!=0):
                check1=k in frontier
                check2=k in explored
                if (check1==False and check2==False):
                    if k==end:
                        cost = 0
                        path.append(k)
                        path.append(res)
                        while True:
                            value=explored[res]
                            res=value
                            if (value==None):
                                path.reverse()
                                for i in range(len(path)-1):
                                    x = path[i]
                                    y = path[i+1]
                                    cost+= matrix[x][y]
                                return cost,path
                            path.append(value)
                        return
                    frontier[k]=res
            k+=1
    return explored, path

In [7]:
def BFS(matrix,start,end):
    path=[]
    explored={}
    frontier={}
    frontier[start]=None
    k=start
    while True:
        if len(frontier)==0:
            result='No path'
            return list(explored),result
        res=list(frontier.keys())[0]
        point=frontier.pop(res)
        explored[res]=point
        value=0
        k=0
        for i in matrix[res]:
            if (i!=0):
                check1=k in frontier
                check2=k in explored
                if (check1==False and check2==False):
                    if k==end:
                        cost = 0
                        path.append(k)
                        path.append(res)
                        while True:
                            value=explored[res]
                            res=value
                            if (value==None):
                                path.reverse()  
                                for i in range(len(path)-1):
                                    x = path[i]
                                    y = path[i+1]
                                    cost+= matrix[x][y]
                                return cost,path
                            path.append(value)
                        return
                    frontier[k]=res
            k+=1
    return explored, path

In [8]:
def GBFS(matrix, start,end,h):
    path = []
    explored = {}
    frontier  = {}
    frontier[start] = [None, h[start]]
    while True:
        if(len(frontier)==0):
            result = 'No path'
            return list(explored), result
        res = list(frontier.keys())[0]
        point = frontier.pop(res)
        explored[res] = point
        k = 0
        value = 0
        for i in matrix[res]:
            if(i!=0):
                check1 = k in frontier
                check2 = k in explored
                if(check1 == False and check2 == False):
                    if(k == end):
                        cost = 0
                        path.append(k)
                        path.append(res)
                        while True:
                            value = explored[res][0]
                            res = value
                            if(value == None):
                                path.reverse()
                                for i in range(len(path)-1):
                                    x = path[i]
                                    y = path[i+1]
                                    cost+= matrix[x][y]
                                return cost, path
                            path.append(value)
                        return
                    frontier[k]=[res,h[k]]
            k+=1
        frontier = dict(sorted(frontier.items(), key= lambda item: item[1][1]))
    return explored, path

In [12]:
def A_star(matrix,start,end,h):
    path=[]
    explored={}
    frontier={}
    frontier[start]=[None,0,h[start]]
    while True:
        if len(frontier)==0:
            result='No path'
            return list(explored),result
        res = list(frontier.keys())[0]
        point = frontier.pop(res)
        explored[res] = point
        value = 0
        if (res == end):
            cost = 0
            path.append(res)
            while True:
                value=explored[res][0]
                res=value
                if (value==None):
                    path.reverse()
                    for i in range(len(path)-1):
                        x = path[i]
                        y = path[i+1]
                        cost+= matrix[x][y]
                    return cost,path
                path.append(value)
            return
        k = 0
        for i in matrix[res]:
            if(i!=0):
                check1 = k in frontier
                check2 = k in explored
                newval = i + explored[res][1] + h[k]
                if(check2 == False):
                    if(check1 == True):
                        if(frontier[k][2]>newval):
                            frontier[k] = [res, i + explored[res][1], newval]
                    elif(check1 == False):
                        frontier[k]=[res, i + explored[res][1], newval]
                else:
                    if(explored[k][2]>newval):
                        explored[k] = []
                        item = explored.pop(k)
                        frontier[k]=item
            k+=1
        frontier = dict(sorted(frontier.items(), key=lambda item: item[1][2]))
    return explored, path

In [13]:
def result_maze(filename):
    f = open("result.txt", 'r+')
    matrix, nodes,pointed_nodes, start, end, start_index, end_index,size,h = read_maze(filename)
    explored, path = A_star(matrix, start_index, end_index,h)
    print(matrix)
    path_1 = []
    for i in path:
        path_1.append(nodes[i])
    path = path_1.copy()
    print(explored, path)
    row = size[0]
    column = size[1]
    result = []
    for i in range(row):
        line =""
        for j in range(column):
            value = ""
            if([i,j] == start):
                value = "S"
            elif([i,j] == end):
                value = "E"
            elif([i,j] in path):
                value = "*"
            elif([i,j] in nodes):
                value = " "
            else:
                value = "x"
            line+=value
        result.append(line)
    for i in range(row):
        f.write(result[i])
        f.write("\n")
    f.close()

In [14]:
result_maze('maze.txt')

[[ 0  1  0 ...  0  0  0]
 [ 1  0 -1 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
13 [[3, 16], [3, 15], [3, 14], [3, 13], [3, 12], [3, 11], [3, 10], [3, 9], [3, 8], [3, 7], [2, 7], [2, 6], [2, 5], [2, 4], [2, 3], [2, 2], [1, 2], [1, 1], [1, 0]]
